# Generated by Django 5.2.5 on 2025-09-18 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('months', models.PositiveIntegerField(help_text='تعداد ماه\u200cهای پرداخت')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plan', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, help_text='مقدار جریمه دیرکرد (در صورت وجود)', max_digits=12)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.installmentplan')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='مبلغ پرداخت شده', max_digits=12)),
                ('payment_method', models.CharField(choices=[('online', 'پرداخت آنلاین'), ('cod', 'پرداخت در محل'), ('card_to_card', 'کارت به کارت'), ('wallet', 'کیف پول داخلی'), ('check', 'چک / سفته (برای اقساط)')], max_length=30)),
                ('tracking_code', models.CharField(blank=True, help_text='کد پیگیری درگاه یا شماره فیش کارت به کارت', max_length=100, null=True)),
                ('proof_image', models.ImageField(blank=True, help_text='تصویر رسید کارت به کارت', null=True, upload_to='payment_proofs/')),
                ('is_successful', models.BooleanField(default=True, help_text='آیا پرداخت موفق بوده؟')),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
        ),
    ]
