# Generated by Django 5.2.5 on 2026-07-28 12:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_alter_order_options_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='مبلغ بر حسب تومان', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مبلغ کل اقساط')),
                ('months', models.PositiveSmallIntegerField(help_text='تعداد ماه\u200cهای بازپرداخت', validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد اقساط')),
                ('monthly_amount', models.DecimalField(decimal_places=2, help_text='مبلغ هر قسط بر حسب تومان', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مبلغ هر قسط')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع اقساط')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('active', 'فعال'), ('completed', 'تسویه\u200cشده'), ('cancelled', 'لغوشده'), ('defaulted', 'دارای بدهی معوق')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت برنامه اقساط')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='installment_plan', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'برنامه اقساط',
                'verbose_name_plural': 'برنامه\u200cهای اقساط',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='مبلغ پرداخت بر حسب تومان', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مبلغ پرداخت')),
                ('payment_method', models.CharField(choices=[('online', 'پرداخت آنلاین'), ('cod', 'پرداخت در محل'), ('card_to_card', 'کارت به کارت'), ('wallet', 'کیف پول'), ('installment', 'پرداخت اقساطی')], db_index=True, default='online', max_length=30, verbose_name='روش پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('processing', 'در حال پردازش'), ('successful', 'موفق'), ('failed', 'ناموفق'), ('cancelled', 'لغوشده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('gateway', models.CharField(blank=True, default='', help_text='مثلاً zarinpal یا idpay', max_length=50, verbose_name='درگاه پرداخت')),
                ('authority', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='شناسه تراکنش درگاه')),
                ('tracking_code', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='کد رهگیری پرداخت')),
                ('reference_id', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='شماره مرجع بانکی')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='پاسخ درگاه')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='پیام خطا')),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='payment_proofs/%Y/%m/', verbose_name='تصویر رسید')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت موفق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='شماره قسط')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('amount', models.DecimalField(decimal_places=2, help_text='مبلغ بر حسب تومان', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مبلغ قسط')),
                ('late_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='مبلغ جریمه بر حسب تومان', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='جریمه دیرکرد')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت\u200cشده'), ('overdue', 'سررسید گذشته'), ('cancelled', 'لغوشده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت قسط')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='payments.installmentplan', verbose_name='برنامه اقساط')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_payment', to='payments.payment', verbose_name='تراکنش پرداخت')),
            ],
            options={
                'verbose_name': 'قسط',
                'verbose_name_plural': 'اقساط',
                'ordering': ['installment_number'],
            },
        ),
        migrations.AddIndex(
            model_name='installmentplan',
            index=models.Index(fields=['status', 'start_date'], name='installment_plan_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'status'], name='payment_order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['authority'], name='payment_authority_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tracking_code'], name='payment_tracking_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentpayment',
            index=models.Index(fields=['status', 'due_date'], name='installment_due_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='installmentpayment',
            constraint=models.UniqueConstraint(fields=('plan', 'installment_number'), name='unique_installment_number_per_plan'),
        ),
    ]
