# Generated by Django 5.2.5 on 2026-06-28 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_slug'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True, help_text='آیا همکاری با این تأمین\u200cکننده فعال است؟'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='note',
            field=models.TextField(blank=True, help_text='یادداشت\u200cهای داخلی مدیر فروشگاه'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='آخرین زمان ویرایش اطلاعات'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, help_text='آدرس دفتر یا انبار', null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاریخ ثبت تأمین\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, help_text='ایمیل', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(help_text='نام شرکت یا فروشنده عمده', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, help_text='شماره تماس', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, help_text='آدرس وب\u200cسایت تأمین\u200cکننده', null=True),
        ),
        migrations.CreateModel(
            name='SupplierOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_product_name', models.CharField(blank=True, help_text='نامی که تأمین\u200cکننده برای این محصول استفاده می\u200cکند.', max_length=300, verbose_name='نام محصول نزد تأمین\u200cکننده')),
                ('supplier_product_code', models.CharField(blank=True, help_text='کد داخلی محصول نزد تأمین\u200cکننده (در صورت وجود)', max_length=100, verbose_name='کد محصول تأمین\u200cکننده')),
                ('supplier_url', models.URLField(help_text='آدرس صفحه محصول در سایت تأمین\u200cکننده', verbose_name='لینک محصول')),
                ('purchase_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت خرید')),
                ('supplier_stock', models.PositiveIntegerField(default=0, verbose_name='موجودی تأمین\u200cکننده')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجود')),
                ('is_primary', models.BooleanField(default=False, help_text='اگر فعال باشد این تأمین\u200cکننده به عنوان تأمین\u200cکننده اصلی محصول استفاده می\u200cشود.', verbose_name='تأمین\u200cکننده اصلی')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='آخرین مشاهده در لیست محصولات')),
                ('last_checked', models.DateTimeField(auto_now=True, verbose_name='آخرین بررسی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('supplier', models.ForeignKey(help_text='تأمین\u200cکننده عرضه\u200cکننده این محصول', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='suppliers.supplier', verbose_name='تأمین\u200cکننده')),
                ('variant', models.ForeignKey(help_text='واریانتی که این تأمین\u200cکننده عرضه می\u200cکند', on_delete=django.db.models.deletion.CASCADE, related_name='supplier_offers', to='products.productvariant', verbose_name='واریانت محصول')),
            ],
            options={
                'verbose_name': 'پیشنهاد تأمین\u200cکننده',
                'verbose_name_plural': 'پیشنهادهای تأمین\u200cکنندگان',
                'ordering': ['supplier', 'variant'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, help_text='قیمت خرید ثبت\u200cشده در این تاریخ.', max_digits=12, verbose_name='قیمت خرید')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='زمان ثبت این تغییر قیمت.', verbose_name='زمان ثبت')),
                ('supplier_offer', models.ForeignKey(help_text='پیشنهاد تأمین\u200cکننده\u200cای که قیمت آن تغییر کرده است.', on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='suppliers.supplieroffer', verbose_name='پیشنهاد تأمین\u200cکننده')),
            ],
            options={
                'verbose_name': 'تاریخچه قیمت تأمین\u200cکننده',
                'verbose_name_plural': 'تاریخچه قیمت تأمین\u200cکنندگان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='supplieroffer',
            constraint=models.UniqueConstraint(fields=('supplier', 'variant'), name='unique_supplier_variant'),
        ),
    ]
