# Generated by Django 5.2.4 on 2026-08-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_supplier_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(help_text=' نامک یکتا برای لینک  ', max_length=255, unique=True),
        ),
    ]
