# Generated by Django 5.2.4 on 2025-11-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام بسته پستی', max_length=100, unique=True)),
                ('length', models.FloatField(help_text='طول بسته به سانتیمتر')),
                ('width', models.FloatField(help_text='عرض بسته به سانتیمتر')),
                ('height', models.FloatField(help_text='ارتفاع بسته به سانتیمتر')),
                ('max_weight', models.FloatField(default=0, help_text='حداکثر وزن مجاز به گرم')),
                ('carton_weight', models.FloatField(default=0, help_text='وزن خود کارتن به گرم')),
                ('carton_type', models.CharField(default='استاندارد', help_text='نوع کارتن (مثلاً استاندارد ایران)', max_length=50)),
            ],
        ),
    ]
