# Generated by Django 5.2.4 on 2026-08-25 03:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazbia_packing', '0001_initial'),
        ('products', '0011_remove_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantShippingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_grams', models.PositiveIntegerField(blank=True, help_text='وزن یک واحد از این تنوع محصول به گرم. این مقدار شامل بسته\u200cبندی اصلی محصول است، اما بسته\u200cبندی حفاظتی اضافه را شامل نمی\u200cشود.', null=True, validators=[django.core.validators.MinValueValidator(1, message='وزن محصول باید بیشتر از صفر باشد.')], verbose_name='وزن محصول به گرم')),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, help_text='طول یک واحد محصول در حالت آماده بسته\u200cبندی و بر حسب سانتی\u200cمتر.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='طول محصول باید بیشتر از صفر باشد.')], verbose_name='طول بسته به سانتی\u200cمتر')),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, help_text='عرض یک واحد محصول در حالت آماده بسته\u200cبندی و بر حسب سانتی\u200cمتر.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='عرض محصول باید بیشتر از صفر باشد.')], verbose_name='عرض بسته به سانتی\u200cمتر')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, help_text='ارتفاع یک واحد محصول در حالت آماده بسته\u200cبندی و بر حسب سانتی\u200cمتر.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='ارتفاع محصول باید بیشتر از صفر باشد.')], verbose_name='ارتفاع بسته به سانتی\u200cمتر')),
                ('extra_packaging_weight_grams', models.PositiveIntegerField(default=0, help_text='وزن تقریبی ضربه\u200cگیر، نایلون، فوم یا سایر مواد بسته\u200cبندی اضافه برای هر واحد محصول، به گرم.', verbose_name='وزن بسته\u200cبندی حفاظتی اضافه')),
                ('is_fragile', models.BooleanField(default=False, help_text='اگر محصول شکستنی است و به مراقبت یا ضربه\u200cگیر بیشتری نیاز دارد، این گزینه فعال شود.', verbose_name='کالای شکستنی')),
                ('requires_separate_package', models.BooleanField(default=False, help_text='اگر محصول نباید همراه سایر محصولات در یک کارتن قرار بگیرد، این گزینه فعال شود.', verbose_name='نیازمند بسته\u200cبندی جداگانه')),
                ('can_rotate', models.BooleanField(default=True, help_text='آیا محصول هنگام چیدمان داخل کارتن می\u200cتواند در جهت\u200cهای مختلف چرخانده شود؟ برای محصولاتی مانند مایعات یا کالاهای دارای جهت نگهداری خاص، این گزینه غیرفعال شود.', verbose_name='قابل چرخش در بسته')),
                ('is_liquid', models.BooleanField(default=False, help_text='اگر محصول حاوی مایع است، این گزینه فعال شود. این اطلاعات می\u200cتواند برای محدودیت چرخش و بسته\u200cبندی ضدنشت استفاده شود.', verbose_name='کالای مایع')),
                ('is_active', models.BooleanField(default=True, help_text='اگر غیرفعال باشد، موتور بسته\u200cبندی نباید از این پروفایل برای محاسبات جدید استفاده کند.', verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('variant', models.OneToOneField(help_text='تنوع محصولی که این مشخصات فیزیکی و ارسال به آن تعلق دارد.', on_delete=django.db.models.deletion.CASCADE, related_name='shipping_profile', to='products.productvariant', verbose_name='تنوع محصول')),
            ],
            options={
                'verbose_name': 'مشخصات ارسال تنوع محصول',
                'verbose_name_plural': 'مشخصات ارسال تنوع\u200cهای محصول',
                'ordering': ['variant__product__name', 'variant__sku'],
            },
        ),
    ]
