# Generated by Django 6.0.6 on 2026-07-26 20:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bazbia_packing", "0002_variantshippingprofile"),
        ("products", "0011_remove_product_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="variantshippingprofile",
            name="can_have_items_on_top",
            field=models.BooleanField(
                default=True,
                help_text="آیا می\u200cتوان محصولات دیگر را روی این محصول قرار داد؟",
                verbose_name="قابل تحمل محصول روی خود",
            ),
        ),
        migrations.AddField(
            model_name="variantshippingprofile",
            name="can_stack_on_others",
            field=models.BooleanField(
                default=True,
                help_text="آیا این محصول می\u200cتواند روی محصول دیگری قرار داده شود؟",
                verbose_name="قابل قرارگیری روی محصولات دیگر",
            ),
        ),
        migrations.AddField(
            model_name="variantshippingprofile",
            name="can_turn_upside_down",
            field=models.BooleanField(
                default=True,
                help_text="آیا محصول می\u200cتواند به\u200cصورت وارونه قرار بگیرد؟",
                verbose_name="قابل وارونه شدن",
            ),
        ),
        migrations.AddField(
            model_name="variantshippingprofile",
            name="compatibility_group",
            field=models.CharField(
                blank=True,
                default="",
                help_text="برای گروه\u200cبندی کالاها مانند food، chemical، liquid یا fragile.",
                max_length=50,
                verbose_name="گروه سازگاری بسته\u200cبندی",
            ),
        ),
        migrations.AddField(
            model_name="variantshippingprofile",
            name="is_chemical",
            field=models.BooleanField(default=False, verbose_name="شیمیایی یا شوینده"),
        ),
        migrations.AddField(
            model_name="variantshippingprofile",
            name="is_food",
            field=models.BooleanField(default=False, verbose_name="خوراکی"),
        ),
        migrations.AddField(
            model_name="variantshippingprofile",
            name="is_hazardous",
            field=models.BooleanField(
                default=False,
                help_text="برای کالاهایی که حمل آن\u200cها نیازمند قوانین خاص است.",
                verbose_name="دارای محدودیت حمل",
            ),
        ),
        migrations.AddField(
            model_name="variantshippingprofile",
            name="max_top_load_grams",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="حداکثر وزن مجاز محصولات قرارگرفته روی این کالا به گرم. خالی یعنی محدودیت عددی ثبت نشده است.",
                null=True,
                verbose_name="حداکثر وزن قابل تحمل روی محصول",
            ),
        ),
        migrations.AddField(
            model_name="variantshippingprofile",
            name="must_remain_upright",
            field=models.BooleanField(
                default=False,
                help_text="محصول نباید روی پهلو یا وارونه قرار بگیرد. چرخش افقی طول و عرض همچنان می\u200cتواند مجاز باشد.",
                verbose_name="باید ایستاده بماند",
            ),
        ),
        migrations.AddField(
            model_name="variantshippingprofile",
            name="notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="توضیحات ویژه برای انباردار یا موتور بسته\u200cبندی.",
                verbose_name="توضیحات بسته\u200cبندی",
            ),
        ),
        migrations.AddField(
            model_name="variantshippingprofile",
            name="padding_cm",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="فضای اضافه موردنیاز در هر طرف محصول به سانتی\u200cمتر. مثلاً مقدار ۱ یعنی دو سانتی\u200cمتر به هر بُعد اضافه می\u200cشود.",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="حاشیه حفاظتی در هر طرف",
            ),
        ),
        migrations.AddField(
            model_name="variantshippingprofile",
            name="requires_bubble_wrap",
            field=models.BooleanField(
                default=False, verbose_name="نیازمند ضربه\u200cگیر"
            ),
        ),
        migrations.AlterField(
            model_name="variantshippingprofile",
            name="can_rotate",
            field=models.BooleanField(
                default=True,
                help_text="اگر فعال باشد موتور می\u200cتواند جهت محصول را برای پیدا کردن چیدمان مناسب تغییر دهد.",
                verbose_name="قابل چرخش",
            ),
        ),
        migrations.AlterField(
            model_name="variantshippingprofile",
            name="extra_packaging_weight_grams",
            field=models.PositiveIntegerField(
                default=0,
                help_text="وزن فوم، نایلون، ضربه\u200cگیر و بسته\u200cبندی اضافی برای هر واحد محصول.",
                verbose_name="وزن بسته\u200cبندی حفاظتی اضافه",
            ),
        ),
        migrations.AlterField(
            model_name="variantshippingprofile",
            name="height_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="ارتفاع به سانتی\u200cمتر",
            ),
        ),
        migrations.AlterField(
            model_name="variantshippingprofile",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AlterField(
            model_name="variantshippingprofile",
            name="is_fragile",
            field=models.BooleanField(default=False, verbose_name="شکستنی"),
        ),
        migrations.AlterField(
            model_name="variantshippingprofile",
            name="is_liquid",
            field=models.BooleanField(default=False, verbose_name="مایع"),
        ),
        migrations.AlterField(
            model_name="variantshippingprofile",
            name="length_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="طول به سانتی\u200cمتر",
            ),
        ),
        migrations.AlterField(
            model_name="variantshippingprofile",
            name="requires_separate_package",
            field=models.BooleanField(
                default=False, verbose_name="نیازمند بسته\u200cبندی جداگانه"
            ),
        ),
        migrations.AlterField(
            model_name="variantshippingprofile",
            name="variant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_profile",
                to="products.productvariant",
                verbose_name="تنوع محصول",
            ),
        ),
        migrations.AlterField(
            model_name="variantshippingprofile",
            name="weight_grams",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="وزن یک واحد محصول همراه با بسته\u200cبندی کارخانه، بدون بسته\u200cبندی حفاظتی بازبیا.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="وزن محصول باید بیشتر از صفر باشد."
                    )
                ],
                verbose_name="وزن محصول به گرم",
            ),
        ),
        migrations.AlterField(
            model_name="variantshippingprofile",
            name="width_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="عرض به سانتی\u200cمتر",
            ),
        ),
    ]
