# Generated by Django 5.2.5 on 2026-07-26 20:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazbia_packing', '0003_variantshippingprofile_can_have_items_on_top_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingbox',
            options={'ordering': ['inner_length_cm', 'inner_width_cm', 'inner_height_cm'], 'verbose_name': 'بسته استاندارد', 'verbose_name_plural': 'بسته\u200cهای استاندارد'},
        ),
        migrations.RemoveField(
            model_name='shippingbox',
            name='carton_type',
        ),
        migrations.RemoveField(
            model_name='shippingbox',
            name='carton_weight',
        ),
        migrations.RemoveField(
            model_name='shippingbox',
            name='height',
        ),
        migrations.RemoveField(
            model_name='shippingbox',
            name='length',
        ),
        migrations.RemoveField(
            model_name='shippingbox',
            name='max_weight',
        ),
        migrations.RemoveField(
            model_name='shippingbox',
            name='width',
        ),
        migrations.AddField(
            model_name='shippingbox',
            name='allows_fragile_items',
            field=models.BooleanField(default=True, verbose_name='مناسب کالای شکستنی'),
        ),
        migrations.AddField(
            model_name='shippingbox',
            name='allows_liquid_items',
            field=models.BooleanField(default=True, verbose_name='مناسب کالای مایع'),
        ),
        migrations.AddField(
            model_name='shippingbox',
            name='code',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='کد بسته'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingbox',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingbox',
            name='empty_weight_grams',
            field=models.PositiveIntegerField(default=0, verbose_name='وزن خالی بسته'),
        ),
        migrations.AddField(
            model_name='shippingbox',
            name='inner_height_cm',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='ارتفاع داخلی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingbox',
            name='inner_length_cm',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='طول داخلی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingbox',
            name='inner_width_cm',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='عرض داخلی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingbox',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='shippingbox',
            name='max_content_weight_grams',
            field=models.PositiveIntegerField(default=20, verbose_name='حداکثر وزن محتویات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingbox',
            name='outer_height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='ارتفاع خارجی'),
        ),
        migrations.AddField(
            model_name='shippingbox',
            name='outer_length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='طول خارجی'),
        ),
        migrations.AddField(
            model_name='shippingbox',
            name='outer_width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='عرض خارجی'),
        ),
        migrations.AddField(
            model_name='shippingbox',
            name='package_type',
            field=models.CharField(choices=[('postal_box', 'جعبه پستی'), ('carton', 'کارتن'), ('envelope', 'پاکت'), ('bubble_envelope', 'پاکت حباب\u200cدار'), ('bag', 'کیسه یا نایلون')], default='postal_box', max_length=30, verbose_name='نوع بسته'),
        ),
        migrations.AddField(
            model_name='shippingbox',
            name='price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت بسته به ریال'),
        ),
        migrations.AddField(
            model_name='shippingbox',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی'),
        ),
        migrations.AddField(
            model_name='shippingbox',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shippingbox',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام بسته'),
        ),
    ]
