# Generated by Django 6.0.6 on 2026-08-08 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0011_remove_product_quantity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("page_view", "بازدید صفحه"),
                            ("product_view", "مشاهده محصول"),
                            ("add_to_cart", "افزودن به سبد"),
                            ("checkout_started", "شروع تسویه حساب"),
                            ("order_created", "ثبت سفارش"),
                            ("order_paid", "پرداخت موفق"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="نوع رویداد",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="کلید نشست",
                    ),
                ),
                (
                    "visitor_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        verbose_name="شناسه بازدیدکننده",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=500,
                        verbose_name="مسیر صفحه",
                    ),
                ),
                (
                    "page_url",
                    models.TextField(blank=True, verbose_name="آدرس کامل صفحه"),
                ),
                (
                    "referrer",
                    models.TextField(blank=True, verbose_name="صفحه ارجاع\u200cدهنده"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="منبع ورودی",
                    ),
                ),
                (
                    "utm_source",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="UTM Source",
                    ),
                ),
                (
                    "utm_medium",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="UTM Medium",
                    ),
                ),
                (
                    "utm_campaign",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=150,
                        verbose_name="UTM Campaign",
                    ),
                ),
                (
                    "utm_content",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="UTM Content"
                    ),
                ),
                (
                    "utm_term",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="UTM Term"
                    ),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, verbose_name="هش IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="اطلاعات اضافی"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="زمان ثبت"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to="products.product",
                        verbose_name="محصول",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to="products.productvariant",
                        verbose_name="تنوع محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "رویداد سایت",
                "verbose_name_plural": "رویدادهای سایت",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="analytics_event_time_idx",
                    ),
                    models.Index(
                        fields=["source", "created_at"],
                        name="analytics_source_time_idx",
                    ),
                    models.Index(
                        fields=["product", "created_at"],
                        name="analytics_product_time_idx",
                    ),
                    models.Index(
                        fields=["visitor_id", "created_at"],
                        name="analytics_visitor_time_idx",
                    ),
                ],
            },
        ),
    ]
