# customers/constants.py

OTP_LENGTH = 6
OTP_EXPIRATION_SECONDS = 120
OTP_REQUEST_COOLDOWN_SECONDS = 60
OTP_MAX_ATTEMPTS = 5

OTP_PURPOSE_LOGIN = "login"
OTP_PURPOSE_PASSWORD_RESET = "password_reset"
