# Generated by Django 6.0.6 on 2026-08-01 06:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0011_remove_product_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="TorobRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("pagination", "دریافت صفحه محصولات"),
                            ("page_uniques", "دریافت با شناسه یکتا"),
                            ("page_urls", "دریافت با لینک محصول"),
                            ("invalid", "درخواست نامعتبر"),
                        ],
                        db_index=True,
                        default="invalid",
                        max_length=20,
                        verbose_name="نوع درخواست",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        default="POST", max_length=10, verbose_name="متد درخواست"
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="مسیر endpoint"
                    ),
                ),
                (
                    "request_body",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="بدنه درخواست"
                    ),
                ),
                (
                    "page",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="شماره صفحه"
                    ),
                ),
                (
                    "sort",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="نوع مرتب\u200cسازی"
                    ),
                ),
                (
                    "requested_items_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="تعداد page_unique یا page_url ارسال\u200cشده توسط ترب.",
                        verbose_name="تعداد آیتم\u200cهای درخواستی",
                    ),
                ),
                (
                    "response_status",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=200, verbose_name="کد وضعیت پاسخ"
                    ),
                ),
                (
                    "products_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد محصولات پاسخ"
                    ),
                ),
                (
                    "total_products",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد کل محصولات"
                    ),
                ),
                (
                    "max_pages",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="تعداد کل صفحات"
                    ),
                ),
                (
                    "auth_status",
                    models.CharField(
                        choices=[
                            ("valid", "توکن معتبر"),
                            ("invalid", "توکن نامعتبر"),
                            ("missing", "توکن ارسال نشده"),
                            ("not_checked", "بررسی نشده"),
                        ],
                        db_index=True,
                        default="not_checked",
                        max_length=20,
                        verbose_name="وضعیت اعتبارسنجی توکن",
                    ),
                ),
                (
                    "token_version",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="نسخه توکن ترب"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="پیام خطا"),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="مدت پاسخ\u200cگویی به میلی\u200cثانیه",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="آدرس IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User-Agent")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="زمان درخواست"
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ درخواست ترب",
                "verbose_name_plural": "لاگ درخواست\u200cهای ترب",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at", "response_status"],
                        name="torob_log_date_status_idx",
                    ),
                    models.Index(
                        fields=["request_type", "-created_at"],
                        name="torob_log_type_date_idx",
                    ),
                    models.Index(
                        fields=["auth_status", "-created_at"],
                        name="torob_log_auth_date_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TorobVariantConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="اگر فعال باشد، این واریانت در صورت داشتن موجودی و قیمت معتبر به ترب ارسال می\u200cشود.",
                        verbose_name="نمایش در ترب",
                    ),
                ),
                (
                    "page_unique",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="شناسه ثابت واریانت در ترب که نباید در طول زمان تغییر کند.",
                        max_length=200,
                        unique=True,
                        verbose_name="شناسه یکتای ترب",
                    ),
                ),
                (
                    "torob_updated_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="آخرین زمانی که اطلاعات ارسالی این واریانت به ترب تغییر کرده است.",
                        verbose_name="آخرین تغییر مؤثر در ترب",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="زمان ویرایش تنظیمات"
                    ),
                ),
                (
                    "variant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="torob_config",
                        to="products.productvariant",
                        verbose_name="واریانت محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات واریانت ترب",
                "verbose_name_plural": "تنظیمات واریانت\u200cهای ترب",
                "ordering": ["-torob_updated_at"],
                "indexes": [
                    models.Index(
                        fields=["is_enabled", "-torob_updated_at"],
                        name="torob_enabled_updated_idx",
                    )
                ],
            },
        ),
    ]
