# Generated by Django 6.0.6 on 2026-08-12 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0011_remove_product_quantity"),
        ("suppliers", "0005_alter_supplier_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("confirmed", "تأیید شده"),
                            ("cancelled", "لغو شده"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("cash", "نقدی"), ("credit", "نسیه")],
                        default="credit",
                        max_length=20,
                        verbose_name="نوع پرداخت",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="شماره فاکتور"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="یادداشت")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ تأیید"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="suppliers.supplier",
                        verbose_name="تأمین\u200cکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "خرید",
                "verbose_name_plural": "خریدها",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="تعداد")),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=14,
                        verbose_name="قیمت خرید هر واحد",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchases.purchase",
                        verbose_name="خرید",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_items",
                        to="products.productvariant",
                        verbose_name="واریانت",
                    ),
                ),
            ],
            options={
                "verbose_name": "آیتم خرید",
                "verbose_name_plural": "آیتم\u200cهای خرید",
                "ordering": ["id"],
            },
        ),
    ]
