# Generated by Django 5.2.5 on 2026-08-03 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(choices=[('order', 'پیگیری سفارش'), ('payment', 'مشکل پرداخت'), ('product', 'سؤال درباره محصول'), ('return', 'مرجوعی و بازگشت کالا'), ('cooperation', 'همکاری با بازبیا'), ('suggestion', 'پیشنهاد یا انتقاد'), ('other', 'سایر موارد')], db_index=True, max_length=30, verbose_name='موضوع')),
                ('order_number', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='شماره سفارش')),
                ('message', models.TextField(max_length=1000, verbose_name='متن پیام')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('reviewing', 'در حال بررسی'), ('answered', 'پاسخ داده شده'), ('closed', 'بسته شده')], db_index=True, default='new', max_length=20, verbose_name='وضعیت')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت مدیر')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='مرورگر کاربر')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='contact_status_created_idx')],
            },
        ),
    ]
