# Generated by Django 5.2.5 on 2025-09-18 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('purchase', 'ورود کالا از تامین\u200cکننده'), ('reserve', 'رزرو موقت برای سفارش'), ('sale', 'فروش قطعی و خروج کالا'), ('cancel', 'لغو سفارش و برگشت رزرو'), ('return', 'مرجوعی از سمت مشتری'), ('adjustment', 'اصلاح دستی موجودی توسط مدیر انبار')], max_length=20)),
                ('quantity', models.IntegerField(help_text='تعداد مثبت یا منفی تغییر یافته در موجودی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='products.productvariant')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='orders.order')),
            ],
            options={
                'verbose_name': 'حرکت موجودی',
                'verbose_name_plural': 'حرکات موجودی',
            },
        ),
    ]
