# Generated by Django 6.0.6 on 2026-08-11 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("products", "0011_remove_product_quantity"),
        ("suppliers", "0005_alter_supplier_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_received",
                    models.PositiveIntegerField(verbose_name="تعداد اولیه"),
                ),
                (
                    "quantity_remaining",
                    models.PositiveIntegerField(verbose_name="تعداد باقی\u200cمانده"),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=14,
                        verbose_name="بهای خرید هر واحد",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ورود"),
                ),
                ("note", models.TextField(blank=True, verbose_name="یادداشت")),
                (
                    "product_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_lots",
                        to="products.productvariant",
                        verbose_name="واریانت",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_lots",
                        to="suppliers.supplier",
                        verbose_name="تأمین\u200cکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "لات موجودی",
                "verbose_name_plural": "لات\u200cهای موجودی",
                "ordering": ["received_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["product_variant", "quantity_remaining"],
                        name="inventory_i_product_512860_idx",
                    )
                ],
            },
        ),
    ]
