# Generated by Django 5.2.5 on 2026-08-15 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorylot'),
        ('orders', '0006_orderitemcostallocation_inventory_lot'),
        ('products', '0011_remove_product_quantity'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorymovement',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'حرکت موجودی', 'verbose_name_plural': 'حرکات موجودی'},
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='purchase_item',
            field=models.OneToOneField(blank=True, help_text='ردیف فاکتور خریدی که این لات از آن ایجاد شده است. برای موجودی\u200cهای قدیمی و اصلاحات دستی می\u200cتواند خالی باشد.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lot', to='purchases.purchaseitem', verbose_name='ردیف خرید'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='products.productvariant', verbose_name='واریانت'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='quantity',
            field=models.IntegerField(help_text='تعداد مثبت یا منفی تغییر یافته در موجودی', verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='orders.order', verbose_name='سفارش مرتبط'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='type',
            field=models.CharField(choices=[('purchase', 'ورود کالا از تأمین\u200cکننده'), ('reserve', 'رزرو موقت برای سفارش'), ('sale', 'فروش قطعی و خروج کالا'), ('cancel', 'لغو سفارش و برگشت رزرو'), ('return', 'مرجوعی از سمت مشتری'), ('adjustment', 'اصلاح دستی موجودی توسط مدیر انبار')], max_length=20, verbose_name='نوع حرکت'),
        ),
    ]
