# Generated by Django 6.0.6 on 2026-09-17 04:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0007_order_shipped_at_order_shipping_tracking_code"),
        ("products", "0011_remove_product_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasalamCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basalam_category_id",
                    models.PositiveBigIntegerField(
                        unique=True, verbose_name="شناسه دسته در باسلام"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="عنوان دسته در باسلام"
                    ),
                ),
                (
                    "commission_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("15.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("99.99")),
                        ],
                        verbose_name="درصد کارمزد",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین تغییر"),
                ),
            ],
            options={
                "verbose_name": "دسته باسلام",
                "verbose_name_plural": "دسته\u200cها و کارمزدهای باسلام",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="BasalamCategoryMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین تغییر"),
                ),
                (
                    "basalam_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bazbia_mappings",
                        to="basalam_integration.basalamcategory",
                        verbose_name="دسته باسلام",
                    ),
                ),
                (
                    "bazbia_category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="basalam_mapping",
                        to="products.category",
                        verbose_name="دسته بازبیا",
                    ),
                ),
            ],
            options={
                "verbose_name": "نگاشت دسته باسلام",
                "verbose_name_plural": "نگاشت دسته\u200cهای باسلام",
            },
        ),
        migrations.CreateModel(
            name="BasalamOrderMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basalam_order_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="شناسه سفارش باسلام"
                    ),
                ),
                (
                    "basalam_status",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="آخرین وضعیت باسلام",
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="آخرین اطلاعات دریافتی"
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="آخرین همگام\u200cسازی"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="basalam_mapping",
                        to="orders.order",
                        verbose_name="سفارش بازبیا",
                    ),
                ),
            ],
            options={
                "verbose_name": "سفارش باسلام",
                "verbose_name_plural": "سفارش\u200cهای باسلام",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="BasalamProductMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basalam_product_id",
                    models.PositiveBigIntegerField(
                        unique=True, verbose_name="شناسه محصول در باسلام"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین همگام\u200cسازی"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, default="", verbose_name="آخرین خطا"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین تغییر"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="basalam_mapping",
                        to="products.product",
                        verbose_name="محصول بازبیا",
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول متصل به باسلام",
                "verbose_name_plural": "محصولات متصل به باسلام",
            },
        ),
        migrations.CreateModel(
            name="BasalamVariationMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basalam_variation_id",
                    models.PositiveBigIntegerField(
                        unique=True, verbose_name="شناسه تنوع در باسلام"
                    ),
                ),
                (
                    "last_synced_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=14,
                        null=True,
                        verbose_name="آخرین قیمت همگام\u200cشده",
                    ),
                ),
                (
                    "last_synced_stock",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="آخرین موجودی همگام\u200cشده",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین همگام\u200cسازی"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, default="", verbose_name="آخرین خطا"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین تغییر"),
                ),
                (
                    "product_mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variation_mappings",
                        to="basalam_integration.basalamproductmapping",
                        verbose_name="محصول متصل به باسلام",
                    ),
                ),
                (
                    "variant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="basalam_mapping",
                        to="products.productvariant",
                        verbose_name="واریانت بازبیا",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنوع متصل به باسلام",
                "verbose_name_plural": "تنوع\u200cهای متصل به باسلام",
            },
        ),
    ]
