# Generated by Django 6.0.6 on 2026-09-22 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basalam_integration", "0001_initial"),
        ("products", "0011_remove_product_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasalamCategoryAttributeSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="پاسخ کامل ویژگی\u200cها"
                    ),
                ),
                (
                    "attributes_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد ویژگی\u200cها"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, default="", verbose_name="آخرین خطا"),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="زمان آخرین دریافت"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "basalam_category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_snapshot",
                        to="basalam_integration.basalamcategory",
                        verbose_name="دسته باسلام",
                    ),
                ),
            ],
            options={
                "verbose_name": "ویژگی\u200cهای دسته باسلام",
                "verbose_name_plural": "ویژگی\u200cهای دسته\u200cهای باسلام",
                "ordering": ("basalam_category__title",),
            },
        ),
        migrations.CreateModel(
            name="BasalamImageMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basalam_file_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="شناسه فایل در باسلام"
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(max_length=64, verbose_name="هش محتوای تصویر"),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="آخرین همگام\u200cسازی"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, default="", verbose_name="آخرین خطا"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "product_image",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="basalam_mapping",
                        to="products.productimage",
                        verbose_name="تصویر محصول بازبیا",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر متصل به باسلام",
                "verbose_name_plural": "تصاویر متصل به باسلام",
            },
        ),
    ]
