# Generated by Django 5.2.4 on 2026-08-22 16:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='otp',
            name='code',
        ),
        migrations.AddField(
            model_name='otp',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش'),
        ),
        migrations.AddField(
            model_name='otp',
            name='code_hash',
            field=models.CharField(default='defult', max_length=128, verbose_name='هش کد تأیید'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default='ddddd', verbose_name='زمان انقضا'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='استفاده شده'),
        ),
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('login', 'ورود'), ('set_password', 'تنظیم رمز'), ('verify_phone', 'تأیید شماره موبایل')], default='login', max_length=20, verbose_name='هدف'),
        ),
        migrations.AddField(
            model_name='otp',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True, unique=True, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.CharField(db_index=True, max_length=11, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['phone', 'purpose', 'is_used'], name='customers_o_phone_8545a2_idx'),
        ),
    ]
