# Generated by Django 5.2.5 on 2026-07-24 02:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_delete_otp_alter_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=11, verbose_name='شماره موبایل')),
                ('code_hash', models.CharField(max_length=128, verbose_name='هش کد تأیید')),
                ('purpose', models.CharField(choices=[('login', 'ورود'), ('set_password', 'تنظیم رمز'), ('verify_phone', 'تأیید شماره موبایل')], default='login', max_length=20, verbose_name='هدف')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField(verbose_name='زمان انقضا')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'purpose', 'is_used'], name='customers_o_phone_8545a2_idx')],
            },
        ),
    ]
