# Generated by Django 5.2.4 on 2026-08-23 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_otp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='otp',
            new_name='otp_phone_purpose_used_idx',
            old_name='customers_o_phone_8545a2_idx',
        ),
    ]
