# Generated by Django 5.2.4 on 2025-09-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, help_text='مسیر ذخیره تصویر در media', null=True, upload_to='avatar/'),
        ),
    ]
