# Generated by Django 5.2.4 on 2026-08-25 03:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_rename_customers_o_phone_8545a2_idx_otp_phone_purpose_used_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'ordering': ['-is_default', '-updated_at'], 'verbose_name': 'آدرس مشتری', 'verbose_name_plural': 'آدرس\u200cهای مشتری'},
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='province',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='استان'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='recipient_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='نام تحویل\u200cگیرنده'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='recipient_phone',
            field=models.CharField(blank=True, default='', max_length=11, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید با 09 شروع شود و ۱۱ رقم باشد.', regex='^09\\d{9}$')], verbose_name='شماره موبایل تحویل\u200cگیرنده'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='address',
            field=models.TextField(verbose_name='نشانی کامل'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='آدرس پیش\u200cفرض'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=10, validators=[django.core.validators.RegexValidator(message='کد پستی باید دقیقاً ۱۰ رقم باشد.', regex='^\\d{10}$')], verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='title',
            field=models.CharField(blank=True, default='', help_text='مثلاً منزل یا محل کار', max_length=50, verbose_name='عنوان آدرس'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش'),
        ),
    ]
