# Generated by Django 6.0.6 on 2026-09-10 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_alter_customeraddress_options_and_more"),
        ("products", "0011_remove_product_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="WishlistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ افزودن"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_items",
                        to="customers.customer",
                        verbose_name="مشتری",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_items",
                        to="products.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "علاقه\u200cمندی",
                "verbose_name_plural": "علاقه\u200cمندی\u200cها",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("customer", "product"),
                        name="unique_customer_wishlist_product",
                    )
                ],
            },
        ),
    ]
