# Generated by Django 5.2.5 on 2025-09-24 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('scrap_abdisite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchedurl',
            name='product',
        ),
        migrations.AddField(
            model_name='watchedurl',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watched_urls', to='products.productvariant'),
        ),
    ]
