# Generated by Django 5.2.4 on 2025-07-15 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_image'),
        ('scrap_abdisite', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchedurl',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='watchedurl',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='watchedurl',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='watchedurl',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watched_urls', to='products.product'),
        ),
        migrations.AddField(
            model_name='watchedurl',
            name='supplier',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='watched_urls', to='suppliers.supplier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watchedurl',
            name='last_checked',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='watchedurl',
            name='last_price',
        ),
        migrations.RemoveField(
            model_name='watchedurl',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='watchedurl',
            name='user',
        ),
    ]
