# Generated by Django 5.2.4 on 2025-08-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_abdisite', '0003_watchedurl_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedurl',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
