# Generated by Django 5.2.5 on 2025-09-18 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='برای کاربران مهمان، کلید سشن ذخیره می\u200cشود.', max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='اگر کاربر لاگین نکرده، این مقدار تهی می\u200cماند.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت (رزرو)'), ('cancelled', 'لغو شده (آزاد شدن رزرو)'), ('paid', 'پرداخت شده'), ('shipped', 'ارسال شده'), ('completed', 'تحویل داده شده')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='جمع کل سفارش پس از تخفیف', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, help_text='قیمت نهایی هر آیتم در لحظه خرید', max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='SalesSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(help_text='تاریخ شروع بازه')),
                ('period_end', models.DateField(help_text='تاریخ پایان بازه')),
                ('total_quantity', models.PositiveIntegerField(default=0, help_text='جمع تعداد فروش در بازه')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='جمع مبلغ فروش در بازه', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='محصولی که این رکورد خلاصه فروش آن است', on_delete=django.db.models.deletion.CASCADE, related_name='sales_summary', to='products.product')),
                ('variant', models.ForeignKey(blank=True, help_text='واریانت محصول، اگر وجود داشته باشد', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_summary', to='products.productvariant')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'period_start'], name='orders_sale_product_fa4374_idx'), models.Index(fields=['period_start'], name='orders_sale_period__f072f3_idx')],
                'unique_together': {('product', 'variant', 'period_start', 'period_end')},
            },
        ),
    ]
