# Generated by Django 5.2.5 on 2025-09-09 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cart_cartitem'),
        ('products', '0005_productimage_source_url_alter_productimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(help_text='تاریخ شروع بازه')),
                ('period_end', models.DateField(help_text='تاریخ پایان بازه')),
                ('total_quantity', models.PositiveIntegerField(default=0, help_text='جمع تعداد فروش در بازه')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='جمع مبلغ فروش در بازه', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='محصولی که این رکورد خلاصه فروش آن است', on_delete=django.db.models.deletion.CASCADE, related_name='sales_summary', to='products.product')),
                ('variant', models.ForeignKey(blank=True, help_text='واریانت محصول، اگر وجود داشته باشد', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_summary', to='products.productvariant')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'period_start'], name='orders_sale_product_fa4374_idx'), models.Index(fields=['period_start'], name='orders_sale_period__f072f3_idx')],
                'unique_together': {('product', 'variant', 'period_start', 'period_end')},
            },
        ),
    ]
