# Generated by Django 5.2.4 on 2026-02-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_cart_session_key_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, help_text='برای کاربران مهمان، کلید سشن ذخیره می\u200cشود.', max_length=40, null=True),
        ),
    ]
