# Generated by Django 6.0.6 on 2026-07-28 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_alter_customeraddress_options_and_more"),
        ("orders", "0003_cart_is_active_alter_cart_session_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="مجموع تخفیف سفارش به تومان",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="items_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="جمع مبلغ کالاها به تومان",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("online", "پرداخت آنلاین"), ("cod", "پرداخت در محل")],
                default="online",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="customers.customeraddress",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="هزینه ارسال به تومان",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_method_code",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_method_title",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_quote_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار پرداخت"),
                    ("cancelled", "لغو شده"),
                    ("paid", "پرداخت شده"),
                    ("shipped", "ارسال شده"),
                    ("completed", "تحویل داده شده"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="مبلغ نهایی قابل پرداخت به تومان",
                max_digits=14,
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "status"], name="orders_orde_user_id_02a211_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["created_at"], name="orders_orde_created_0e92de_idx"
            ),
        ),
    ]
