# Generated by Django 5.2.4 on 2026-08-11 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options_order_discount_amount_and_more'),
        ('suppliers', '0005_alter_supplier_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemCostAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('internal', 'انبار داخلی'), ('supplier', 'تأمین\u200cکننده')], max_length=20, verbose_name='منبع تأمین')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=0, help_text='بهای خرید هر واحد در لحظه ثبت سفارش. برای موجودی داخلی تا زمان تکمیل سیستم بهای انبار می\u200cتواند خالی باشد.', max_digits=14, null=True, verbose_name='بهای خرید هر واحد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_allocations', to='orders.orderitem', verbose_name='آیتم سفارش')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_cost_allocations', to='suppliers.supplier', verbose_name='تأمین\u200cکننده')),
                ('supplier_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_cost_allocations', to='suppliers.supplieroffer', verbose_name='پیشنهاد تأمین\u200cکننده')),
            ],
            options={
                'verbose_name': 'منبع بهای آیتم سفارش',
                'verbose_name_plural': 'منابع بهای آیتم\u200cهای سفارش',
            },
        ),
    ]
