# Generated by Django 6.0.6 on 2026-08-11 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_inventorylot"),
        ("orders", "0005_orderitemcostallocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitemcostallocation",
            name="inventory_lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_cost_allocations",
                to="inventory.inventorylot",
                verbose_name="لات موجودی داخلی",
            ),
        ),
    ]
