# Generated by Django 6.0.6 on 2026-09-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_orderitemcostallocation_inventory_lot"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipped_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="زمان ارسال"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_tracking_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=100,
                verbose_name="کد رهگیری مرسوله",
            ),
        ),
    ]
