# Generated by Django 5.2.5 on 2026-08-10 12:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دوره مالی')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('is_closed', models.BooleanField(default=False, verbose_name='بسته شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'دوره مالی',
                'verbose_name_plural': 'دوره\u200cهای مالی',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='کد حساب')),
                ('name', models.CharField(max_length=150, verbose_name='نام حساب')),
                ('account_type', models.CharField(choices=[('asset', 'دارایی'), ('liability', 'بدهی'), ('equity', 'سرمایه'), ('income', 'درآمد'), ('expense', 'هزینه')], max_length=20, verbose_name='نوع حساب')),
                ('allow_posting', models.BooleanField(default=True, verbose_name='امکان ثبت سند')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account', verbose_name='حساب والد')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'حساب\u200cها',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField(unique=True, verbose_name='شماره سند')),
                ('entry_type', models.CharField(choices=[('sale', 'فروش'), ('purchase', 'خرید'), ('receipt', 'دریافت'), ('payment', 'پرداخت'), ('expense', 'هزینه'), ('refund', 'برگشت وجه'), ('gateway_settlement', 'تسویه درگاه'), ('supplier_settlement', 'تسویه تأمین\u200cکننده'), ('adjustment', 'اصلاحی'), ('opening', 'افتتاحیه'), ('closing', 'اختتامیه')], max_length=30, verbose_name='نوع سند')),
                ('date', models.DateField(verbose_name='تاریخ سند')),
                ('description', models.TextField(blank=True, verbose_name='شرح سند')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('posted', 'ثبت نهایی'), ('cancelled', 'باطل\u200cشده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='نوع مرجع')),
                ('reference_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='شناسه مرجع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.fiscalperiod', verbose_name='دوره مالی')),
            ],
            options={
                'verbose_name': 'سند حسابداری',
                'verbose_name_plural': 'اسناد حسابداری',
                'ordering': ['-date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='JournalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18, verbose_name='بدهکار')),
                ('credit', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18, verbose_name='بستانکار')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='شرح ردیف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_items', to='accounting.account', verbose_name='حساب')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.journalentry', verbose_name='سند')),
            ],
            options={
                'verbose_name': 'ردیف سند',
                'verbose_name_plural': 'ردیف\u200cهای سند',
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['reference_type', 'reference_id'], name='accounting__referen_4bf694_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['date', 'status'], name='accounting__date_324b4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalitem',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0)), name='journal_item_debit_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='journalitem',
            constraint=models.CheckConstraint(condition=models.Q(('credit__gte', 0)), name='journal_item_credit_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='journalitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('credit', 0), ('debit__gt', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='journal_item_debit_or_credit'),
        ),
    ]
