# Generated by Django 6.0.6 on 2026-08-10 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_number",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="آخرین شماره سند"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fiscal_period",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_sequence",
                        to="accounting.fiscalperiod",
                        verbose_name="دوره مالی",
                    ),
                ),
            ],
            options={
                "verbose_name": "شمارنده سند",
                "verbose_name_plural": "شمارنده\u200cهای اسناد",
            },
        ),
    ]
