# Generated by Django 6.0.6 on 2026-08-17 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0006_orderitemcostallocation_inventory_lot"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[("order_paid", "پرداخت موفق سفارش")],
                        max_length=30,
                        verbose_name="رویداد",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("sms", "پیامک مشتری"), ("admin_email", "ایمیل مدیر")],
                        max_length=30,
                        verbose_name="کانال",
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        blank=True, default="", max_length=254, verbose_name="گیرنده"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار ارسال"),
                            ("sent", "ارسال\u200cشده"),
                            ("failed", "ناموفق"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد تلاش"),
                ),
                (
                    "provider_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="پاسخ سرویس\u200cدهنده"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, default="", verbose_name="آخرین خطا"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان ارسال"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_deliveries",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_deliveries",
                        to="payments.payment",
                        verbose_name="پرداخت",
                    ),
                ),
            ],
            options={
                "verbose_name": "ارسال اعلان",
                "verbose_name_plural": "ارسال اعلان\u200cها",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("payment", "event", "channel"),
                        name="unique_payment_event_channel",
                    )
                ],
            },
        ),
    ]
