# Generated by Django 5.2.5 on 2025-09-25 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='مسیر ذخیره تصویر واریانت در media', null=True, upload_to='variant_images/')),
                ('source_url', models.URLField(blank=True, help_text='لینک تصویر اصلی واریانت از تأمین\u200cکننده (اختیاری)', null=True, unique=True)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_main', models.BooleanField(default=False, help_text='تصویر اصلی واریانت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productvariant')),
            ],
        ),
    ]
