# Generated by Django 5.2.4 on 2025-09-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productvariantimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='قیمت پس از تخفیف (اختیاری)', max_digits=12, null=True),
        ),
    ]
