# Generated by Django 5.2.5 on 2025-10-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_base_price_alter_productvariant_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='source_url',
            field=models.URLField(blank=True, help_text='لینک تصویر اصلی از تأمین\u200cکننده (اختیاری)', null=True),
        ),
    ]
