# Generated by Django 5.2.4 on 2025-08-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_specialproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='source_url',
            field=models.URLField(blank=True, help_text='لینک تصویر اصلی از تأمین\u200cکننده (اختیاری)', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, help_text='مسیر ذخیره تصویر در media', null=True, upload_to='product_images/'),
        ),
    ]
