# Generated by Django 5.2.5 on 2025-10-22 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productimage_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='profit_percent',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='درصد سود محصول بر اساس قیمت خرید', max_digits=5),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='قیمت خرید از تأمین\u200cکننده', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(help_text='نام ویژگی (مثلا رنگ یا سایز)', max_length=50),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='attribute',
            field=models.ForeignKey(help_text='ویژگی مرتبط', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.attribute'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='value',
            field=models.CharField(help_text='مقدار ویژگی (مثلا قرمز یا XL)', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='تصویر دسته\u200cبندی', null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='نام دسته\u200cبندی', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='دسته\u200cبندی والد (اختیاری)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='products.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='نامک یکتا برای URL', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=0, help_text='قیمت پایه محصول', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='دسته\u200cبندی اصلی محصول', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاریخ ایجاد محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات محصول', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='آیا محصول فعال و قابل فروش است'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='نام محصول', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, help_text='موجودی کلی محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='نامک یکتا برای URL', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='تگ\u200cهای مرتبط با محصول', related_name='products', to='products.tag'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='تاریخ آخرین بروزرسانی محصول'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='متن جایگزین تصویر برای SEO', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاریخ ایجاد تصویر'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, help_text='فایل تصویر محصول', null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_main',
            field=models.BooleanField(default=False, help_text='آیا تصویر اصلی محصول است؟'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(help_text='محصول مرتبط با تصویر', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='source_url',
            field=models.URLField(blank=True, help_text='لینک تصویر از تأمین\u200cکننده', null=True),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='name',
            field=models.CharField(help_text='نام مشخصه (مثلا وزن، جنس)', max_length=100),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='product',
            field=models.ForeignKey(help_text='محصول مرتبط', on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='value',
            field=models.TextField(help_text='مقدار مشخصه (مثلا 1 کیلوگرم، فلز)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='attributes',
            field=models.ManyToManyField(blank=True, help_text='ویژگی\u200cهای مرتبط با این واریانت', related_name='variants', to='products.attributevalue'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاریخ ایجاد واریانت'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='تاریخ انقضای محصول (اختیاری)', null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='آستانه هشدار اتمام موجودی'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text='قیمت فروش محصول', max_digits=12),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(help_text='محصول مرتبط', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(help_text='کد اختصاصی واریانت برای انبار', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='موجودی واریانت'),
        ),
        migrations.AlterField(
            model_name='productvariantimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='متن جایگزین تصویر برای SEO', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productvariantimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاریخ ایجاد تصویر واریانت'),
        ),
        migrations.AlterField(
            model_name='productvariantimage',
            name='image',
            field=models.ImageField(blank=True, help_text='فایل تصویر واریانت', null=True, upload_to='variant_images/'),
        ),
        migrations.AlterField(
            model_name='productvariantimage',
            name='is_main',
            field=models.BooleanField(default=False, help_text='آیا این تصویر به عنوان تصویر اصلی واریانت استفاده شود؟'),
        ),
        migrations.AlterField(
            model_name='productvariantimage',
            name='source_url',
            field=models.URLField(blank=True, help_text='لینک تصویر اصلی واریانت از تأمین\u200cکننده (اختیاری)', null=True),
        ),
        migrations.AlterField(
            model_name='productvariantimage',
            name='variant',
            field=models.ForeignKey(help_text='واریانت مرتبط با تصویر', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productvariant'),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='caption',
            field=models.CharField(blank=True, help_text='توضیح یا کپشن ویدئو', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاریخ ایجاد ویدئو'),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='product',
            field=models.ForeignKey(help_text='محصول مرتبط با ویدئو', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='video',
            field=models.FileField(help_text='فایل ویدئو', upload_to='product_videos/'),
        ),
        migrations.AlterField(
            model_name='specialproduct',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='تاریخ پایان ویژه بودن', null=True),
        ),
        migrations.AlterField(
            model_name='specialproduct',
            name='is_active',
            field=models.BooleanField(default=True, help_text='آیا محصول ویژه فعال است؟'),
        ),
        migrations.AlterField(
            model_name='specialproduct',
            name='product',
            field=models.OneToOneField(help_text='محصول ویژه', on_delete=django.db.models.deletion.CASCADE, related_name='special', to='products.product'),
        ),
        migrations.AlterField(
            model_name='specialproduct',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='تاریخ شروع ویژه بودن', null=True),
        ),
        migrations.AlterField(
            model_name='specialproduct',
            name='title',
            field=models.CharField(blank=True, help_text='عنوان ویژه برای نمایش', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='نام تگ', max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='نامک یکتا برای URL', unique=True),
        ),
    ]
