# Generated by Django 5.2.5 on 2025-11-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_pricechangelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='profit_percent',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='درصد سود محصول بر اساس قیمت خرید', max_digits=5),
        ),
    ]
