# Generated by Django 5.2.5 on 2025-12-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productvariant_profit_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='نامک یکتا برای URL', max_length=120, unique=True),
        ),
    ]
