# Generated by Django 5.2.5 on 2026-07-05 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='purchase_price',
        ),
    ]
