# Generated by Django 5.2.4 on 2026-08-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_productvariant_purchase_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
